First pull request
mricanho/Hello-Microverse pull request #1
Opened 2021-05-25 05:11 UTC by mricanho

In this pull request, I finish the project with a beautiful "Hello Microverse"

2021-05-27 19:09 UTC, Shaher-11 reviewed
Hello @mricanho 

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [x] You need to use display:inline-block as the width will not apply on the h1 tag
- [x] aligning the border is not working as expected

## Optional Suggestions 💡
_The following post are highly recommend to improve your code quality, Please consider implementing them

- The commits have to be more descriptive so instead of `Add files` maybe `Add section and style section head`

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-05-27 19:09 UTC, Shaher-11 commented on style.css
> +  border: 3px solid green;
Please make sure to align the border as it's not aligned properly now

2021-05-27 19:09 UTC, Shaher-11 commented on style.css
> +  width: 50%;
You need to use `display:inline-block` if you wish to specify the width of h1 tag

2021-05-27 19:11 UTC, Shaher-11 requested changes
Hello @mricanho 

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [x] You need to use display:inline-block as the width will not apply on the h1 tag
- [ ] aligning the border is not working as expected

## Optional Suggestions 💡
_The following post are highly recommend to improve your code quality, Please consider implementing them

- The commits have to be more descriptive so instead of `Add files` maybe `Add section and style section head`

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-05-28 02:01 UTC, jubaan approved these changes
Hi @mricanho , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-21 17:05 UTC, closed without merging